Add getEngine and all engines
Test plan:
* Get an existing engine. Returns
  a function.
* Get a non-existing engine.
  Returns undefined.
* Add a compilation error in the
  required engine - prints an error
  message and process.exit(1)